Level 2
SergeyZu/moves-explorer-frontend pull request #1
Opened 2023-07-19 09:35 UTC by SergeyZu

2023-07-19 10:50 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

- https://yadi.sk/d/fsWU0Ww7gE7ePA на главной странице пользователь не авторизован, следует отобразить кнопки Вход/Регистрация
- Карточка с сохраненными фильмами не соотв. макету https://yadi.sk/d/oh69-rGXNZbu6g (изначально поля заблокированы, после нажатия Редактировать - доступны и меняется нижняя панель кнопок.)
- https://yadi.sk/d/T_gm1ZqseG3arw всем страницам на уровне родительского блока следует установить высоту равную высоте вьюпорта. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, а шапка прижата к верху, а футер к низу. Также на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).

Общие
- 320 https://yadi.sk/d/ZAIjxzpaDSfYNg лого

Главная страница
- 768 https://yadi.sk/d/rPB-vg8Al6sUsw ширина фото, параметры текста, отступ до ссылки

Меню
- 320 https://yadi.sk/d/1bBXbWg8i_AcgQ

Вход/РЕгистрация
- 320 https://yadi.sk/d/doPr-_58Xh68Wg https://yadi.sk/d/5DexdblyOV5mZw

404
- 320 https://yadi.sk/d/JT6IV_qBNejXeQ

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

* https://yadi.sk/d/2JYDVanED4Intg Обратите внимание, что при сужении экрана образуется горизонтальный скролл. Это чаще всего происходит когда элементы не влезают по ширине, стоит проверить фиксированные ширины, размеры заголовков и перестройку сетки на брейкпоинтах, внести соотв. изменения. Помните также, что медиа запросы должны быть сгруппированы, не менее 150-200п разницей.

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

* https://yadi.sk/d/rwQGQ4IMsxonvw https://yadi.sk/d/_RX9AVnmeuuIUA есть ошибки по БЭМ, для переключения состояний следует создать простые модификаторы, также элементы не располагают внутри себя такие же и размещать без блока. Вам следует самостоятельно на примере найти и исправить все похожие случаи. Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

* https://yadi.sk/i/Su9cmAYpb_ps7Q https://yadi.sk/d/voNs7nvZT9yT9A https://yadi.sk/i/3fdXlBgfLLjpIg https://yadi.sk/i/n_EvqBug40WevQ https://yadi.sk/i/AKR-7sBuEiLZKQ В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи
* https://yadi.sk/i/TLjdG0Ij8jsExw при сужении карточек с фильмами образуется неравномерное расстояние между ними не соотв. макету, можно сделать их ширину резиновой, или расположить выравнивание по центру

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

- https://yadi.sk/d/MR3TR9wXtrnjqw https://yadi.sk/i/Ar-zv3iHvmk5rA https://yadi.sk/d/phlgORhqlE70yA https://yadi.sk/d/iUparGiYDY1ABg Из main следует вытянуть header footer, также следите, чтобы на каждой странице был main, главные раздулы оформлены section
- filter-checkbox используйте чекбокс для оформления элемента формы поиска
- footer__text рекомендуется добавить к каждой секции сем. заголовок, следите за иерархией
- header-main__auth-block используйте тег навигации
- page-not-found__err-code каждой странице нужен заголовок 1 уровня (один)
- navtab внутри ссылки можно расположить контент без кнопок, ссылку стилизовать как кнопку
- search-form__line для подчеркивания используйте стилизацию нижней границы, чтобы не перегружать разметку

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

* https://yadi.sk/i/s2sFQMzSZLKYwA на странице Профиль используйте логику по макету

- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

* https://yadi.sk/d/bDihGdjHicmcew активная вкладка на странице имеет отличную толщину по макету, https://yadi.sk/d/ZsNy7XvQvrJ1lA а также подчеркивание
* https://yadi.sk/d/vCJHgcDD_vXg_Q нет курсора и ховер эффекта

- [ ] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.

- https://yadi.sk/d/Srhpuqeyc1Aqgw рекомендуется пересмотреть кол-во отдельных компонентов для логически одинаковых кнопок и ссылок, частично можно их слить с большими компонентами, например, в навигацию - ссылки вход/регистрация, кнопка лайк/удалить в карточку с фильмами и т.д. (все кнопки оформите button или a href, не селектор img)
- login/register - выглядит как один компонент

- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

* https://yadi.sk/d/o7yXui8I_qa3AA Всем полям следует установить placeholder со значениями, напр., `placeholder="Ваше имя..."`
* Поля должны проходить валидацию, чтобы отображался статус ошибки когда поле заполнено некорректно или пустое, помогут (type, reguired)

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 50

## Доп. Комментарии:
- язык проекта рус [...]

2023-07-22 07:29 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово 2 ревью Вашей работы. Немного нехватило до принятия, есть еще возможность поработать над улчшением

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

- Карточка с сохраненными фильмами не соотв. макету https://yadi.sk/d/S_ja-G2mzpmMXA

Меню
- 320 https://yadi.sk/d/8Cd4SOrN4VDkHg

404
- 320 https://yadi.sk/d/vOxRThpoVM2x1Q

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

* https://yadi.sk/d/SaWp11L9ERYXbQ сохраняются ошибки по БЭМ. Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/

- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

- form-auth__title отдельная страница - заголовок 1 уровня
- https://yadi.sk/d/BP7lLkoG1rqbVA  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox используйте чекбокс для оформления элемента формы поиска
- navtab внутри ссылки можно расположить контент без кнопок, ссылку стилизовать как кнопку

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

* https://yadi.sk/d/bDihGdjHicmcew активная вкладка на странице имеет отличную толщину по макету, https://yadi.sk/d/ZsNy7XvQvrJ1lA а также подчеркивание

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 77

## Доп. Комментарии:

2023-07-22 16:31 UTC, SergeyZu commented
Варвара, благодарю вас за качественное ревью моей работы. 
На многие моменты, которые я даже не заметил в макете вы обратили мое внимание.
Кое над чем мне пришлось попыхтеть, что-то еще и сейчас не до конца понятно.
Но в любом случае, проблемные моменты обозначены, буду с ними разбираться.
Поэтому прошу вас не воспринимать не исправленные замечания как раздолбайство с моей стороны и отношение "на отвяжись".
В данный момент самый критически важный ресурс для меня - это время, и поэтому какие-то моменты, которые вызывают у меня затруднения откладываю "на потом".
Спасибо вам за советы, за ссылки на полезные материалы.
Стараюсь ими воспользоваться, но не всегда получается.
Не разобрался, как пользоваться BEMValidator-ом. Вроде простой сервис, но у меня почему-то не хочет работать.
Копирую код из VSCode жму на validate - и во всех случаях один ответ: "BEMissimo 🤌 (Everything good)"

2023-07-23 07:12 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово 3 ревью Вашей работы. Для принятия все еще остается набрать 3 балла. Постаралась подробнее расписать то что осталось. Необходимо добавить карточку с сохраненным фильмом на ее страницу (там крестик, вместо лайка), также удалить селектор checkbox в двух местах (такого нет), уверена, что у Вас все получится, старайтесь хорошо отдыхать, процесс учебы довольно трудоемкий, чтобы новый материал усвоился. Желаю Вам успеха!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

- https://yadi.sk/d/lnnCBiNVztEx8w Карточка с сохраненными фильмами имеет вместо лайка крестик, чтобы удалить из сохраненных, в дефолтном состоянии он не виден (прозрачен), при наведении появляется.

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

* https://yadi.sk/d/4-v_Th17UWmZEQ Для того, чтобы проверить ошибки по БЭМ, Вам следует скопировать страницу целиком в панеле разработчика, т.к. в компонентах применяется разметка jsx, а нужна html. Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/

- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

- селектор checkbox следует удалить (такого не сужествует), вместо него для оформления поля "Короткометражки" следует использовать `<input type="checkbox">` https://yadi.sk/d/BP7lLkoG1rqbVA  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox используйте чекбокс для оформления элемента формы поиска
- navtab внутри ссылки можно расположить контент без кнопок, ссылку стилизовать как кнопку
- movies-card__like используйте button (вместо checkbox) для кнопки лайк в карточке фильма. Добавляйте модификатор для смены состояния на активный.

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

* https://yadi.sk/d/JOLZxPntFJnWOg обратите внимание в макете на соотв. странице выделена активная вкладка и она имеет толщину 500. Для таких случаев принято создавать булевый модификатор, например, `_active` у ссылки, чтобы его применять на активной странице. https://yadi.sk/d/7iuhXTVVTDmSDg В мобильном меню вместо толщины появляется подчеркивание.

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 77

## Доп. Комментарии:

2023-07-23 15:16 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
Поздравляю, Ваша работа принята! Желаю Вам всего наилучшего в будущей профессии.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

- селектор checkbox следует удалить (такого не сужествует), вместо него для оформления поля "Короткометражки" следует использовать `<input type="checkbox">` https://yadi.sk/d/BP7lLkoG1rqbVA  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox используйте чекбокс для оформления элемента формы поиска
- navtab внутри ссылки можно расположить контент без кнопок, ссылку стилизовать как кнопку
- movies-card__like используйте button (вместо checkbox) для кнопки лайк в карточке фильма. Добавляйте модификатор для смены состояния на активный.

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

* https://yadi.sk/d/JOLZxPntFJnWOg обратите внимание в макете на соотв. странице выделена активная вкладка и она имеет толщину 500. Для таких случаев принято создавать булевый модификатор, например, `_active` у ссылки, чтобы его применять на активной странице. https://yadi.sk/d/7iuhXTVVTDmSDg В мобильном меню вместо толщины появляется подчеркивание.

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 94

## Доп. Комментарии:

2023-07-24 00:45 UTC, merged